{{- if .Values.config.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ravenrustrag.fullname" . }}
  labels:
    {{- include "ravenrustrag.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.config.apiKey | b64enc | quote }}
{{- end }}
